// <auto-generated />
using System;
using IcecreamApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IcecreamApp.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240911144026_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.Icecream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Icecreams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_0.jpg",
                            Name = "Vanilla",
                            Price = 6.2000000000000002
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_1.jpg",
                            Name = "Chocolate",
                            Price = 3.5899999999999999
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_2.jpg",
                            Name = "Strawberry",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_3.jpg",
                            Name = "Mint",
                            Price = 7.9900000000000002
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_4.jpg",
                            Name = "Caramel",
                            Price = 2.9900000000000002
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_5.jpg",
                            Name = "Pistachio",
                            Price = 5.29
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_6.jpg",
                            Name = "Cookie Dough",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_7.jpg",
                            Name = "Lemon",
                            Price = 3.4500000000000002
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_8.jpg",
                            Name = "Coffee",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_9.jpg",
                            Name = "Coconut",
                            Price = 3.6899999999999999
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_10.jpg",
                            Name = "Mango",
                            Price = 1.0900000000000001
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_11.jpg",
                            Name = "Blueberry",
                            Price = 14.99
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_12.jpg",
                            Name = "Raspberry",
                            Price = 5.0
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_13.jpg",
                            Name = "Butter Pecan",
                            Price = 6.5899999999999999
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_14.jpg",
                            Name = "Peach",
                            Price = 1.99
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_15.jpg",
                            Name = "Cookies and Cream",
                            Price = 3.3399999999999999
                        },
                        new
                        {
                            Id = 17,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_16.jpg",
                            Name = "Rocky Road",
                            Price = 5.4199999999999999
                        },
                        new
                        {
                            Id = 18,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_17.jpg",
                            Name = "Cherry",
                            Price = 2.4900000000000002
                        },
                        new
                        {
                            Id = 19,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_18.jpg",
                            Name = "Blackberry",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            Id = 20,
                            Image = "https://github.com/Abhayprince/Images-Icons/blob/main/Icecreams/hq/ic_19.jpg",
                            Name = "Tiramisu",
                            Price = 4.9900000000000002
                        });
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.IcecreamOptions", b =>
                {
                    b.Property<int>("IcecreamId")
                        .HasColumnType("integer");

                    b.Property<string>("Flavor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Topping")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IcecreamId", "Flavor", "Topping");

                    b.ToTable("IcecreamOptions");

                    b.HasData(
                        new
                        {
                            IcecreamId = 1,
                            Flavor = "Vanilla",
                            Topping = "Chocolate Chips"
                        },
                        new
                        {
                            IcecreamId = 1,
                            Flavor = "Vanilla",
                            Topping = "Caramel Drizzle"
                        },
                        new
                        {
                            IcecreamId = 2,
                            Flavor = "Chocolate",
                            Topping = "Whipped Cream"
                        },
                        new
                        {
                            IcecreamId = 3,
                            Flavor = "Strawberry",
                            Topping = "Sprinkles"
                        },
                        new
                        {
                            IcecreamId = 3,
                            Flavor = "Strawberry",
                            Topping = "White Chocolate"
                        },
                        new
                        {
                            IcecreamId = 4,
                            Flavor = "Mint",
                            Topping = "Oreo Crumbles"
                        },
                        new
                        {
                            IcecreamId = 4,
                            Flavor = "Mint",
                            Topping = "Chocolate Sauce"
                        },
                        new
                        {
                            IcecreamId = 5,
                            Flavor = "Caramel",
                            Topping = "Pecans"
                        },
                        new
                        {
                            IcecreamId = 5,
                            Flavor = "Caramel",
                            Topping = "Sea Salt"
                        },
                        new
                        {
                            IcecreamId = 6,
                            Flavor = "Pistachio",
                            Topping = "Almonds"
                        },
                        new
                        {
                            IcecreamId = 7,
                            Flavor = "Cookie Dough",
                            Topping = "Caramel Drizzle"
                        },
                        new
                        {
                            IcecreamId = 7,
                            Flavor = "Cookie Dough",
                            Topping = "Chocolate Chips"
                        },
                        new
                        {
                            IcecreamId = 8,
                            Flavor = "Lemon",
                            Topping = "Coconut Flakes"
                        },
                        new
                        {
                            IcecreamId = 9,
                            Flavor = "Coffee",
                            Topping = "Hazelnuts"
                        },
                        new
                        {
                            IcecreamId = 9,
                            Flavor = "Coffee",
                            Topping = "Cinnamon"
                        },
                        new
                        {
                            IcecreamId = 10,
                            Flavor = "Coconut",
                            Topping = "Pineapple"
                        },
                        new
                        {
                            IcecreamId = 11,
                            Flavor = "Mango",
                            Topping = "Passionfruit Sauce"
                        },
                        new
                        {
                            IcecreamId = 12,
                            Flavor = "Blueberry",
                            Topping = "Granola"
                        },
                        new
                        {
                            IcecreamId = 12,
                            Flavor = "Blueberry",
                            Topping = "White Chocolate"
                        },
                        new
                        {
                            IcecreamId = 13,
                            Flavor = "Raspberry",
                            Topping = "White Chocolate"
                        },
                        new
                        {
                            IcecreamId = 13,
                            Flavor = "Raspberry",
                            Topping = "Dark Chocolate"
                        },
                        new
                        {
                            IcecreamId = 14,
                            Flavor = "Butter Pecan",
                            Topping = "Maple Syrup"
                        },
                        new
                        {
                            IcecreamId = 14,
                            Flavor = "Butter Pecan",
                            Topping = "Crushed Nuts"
                        },
                        new
                        {
                            IcecreamId = 15,
                            Flavor = "Peach",
                            Topping = "Crushed Graham Crackers"
                        },
                        new
                        {
                            IcecreamId = 16,
                            Flavor = "Cookies and Cream",
                            Topping = "Chocolate Sauce"
                        },
                        new
                        {
                            IcecreamId = 16,
                            Flavor = "Cookies and Cream",
                            Topping = "Caramel Sauce"
                        },
                        new
                        {
                            IcecreamId = 17,
                            Flavor = "Rocky Road",
                            Topping = "Mini Marshmallows"
                        },
                        new
                        {
                            IcecreamId = 18,
                            Flavor = "Cherry",
                            Topping = "Crushed Almonds"
                        },
                        new
                        {
                            IcecreamId = 19,
                            Flavor = "Blackberry",
                            Topping = "Walnuts"
                        },
                        new
                        {
                            IcecreamId = 20,
                            Flavor = "Tiramisu",
                            Topping = "Cocoa Powder"
                        },
                        new
                        {
                            IcecreamId = 20,
                            Flavor = "Tiramisu",
                            Topping = "Espresso Drizzle"
                        });
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("OrderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IcecreamId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Topping")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.IcecreamOptions", b =>
                {
                    b.HasOne("IcecreamApp.Api.Data.Entities.Icecream", "Icecream")
                        .WithMany("Options")
                        .HasForeignKey("IcecreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Icecream");
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("IcecreamApp.Api.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.Icecream", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("IcecreamApp.Api.Data.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
